// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Medicine.Infrastructure.Implementation.DataAccesPsql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231112180725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("TransatedEntityWithDescriptionSequence");

            modelBuilder.Entity("DrugDrugCategory", b =>
                {
                    b.Property<int>("DrugCategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("DrugsId")
                        .HasColumnType("integer");

                    b.HasKey("DrugCategoriesId", "DrugsId");

                    b.HasIndex("DrugsId");

                    b.ToTable("DrugDrugCategory");
                });

            modelBuilder.Entity("Medicine.Entities.Models.ActiveElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DrugId");

                    b.ToTable("ActiveElements");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MedicineWorker",
                            NormalizedName = "MEDICINEWORKER"
                        });
                });

            modelBuilder.Entity("Medicine.Entities.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("TimeZone")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Medicine.Entities.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("CourseType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TherapyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseGroupID");

                    b.HasIndex("TherapyId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Medicine.Entities.Models.CourseSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSettings");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DosageRecommendationId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DosageRecommendationId");

                    b.ToTable("DosageLogs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalInDays")
                        .HasColumnType("integer");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DrugId");

                    b.ToTable("DosingFrequencies");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequencyReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DosingFrequencyId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("ReminderId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DosingFrequencyId");

                    b.HasIndex("ReminderId");

                    b.ToTable("DosingFrequencyReminders");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OneUnitSizeInGramm")
                        .HasColumnType("double precision");

                    b.Property<int>("SimilarDrugsId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SimilarDrugsId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DrugCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("DrugCategories");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TimeInUtc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Medicine.Entities.Models.ReminderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrpition")
                        .HasColumnType("text");

                    b.Property<int>("ReminderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReminderLogStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("ReminderLogs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.SimilarDrugs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SimilarDrugs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"TransatedEntityWithDescriptionSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDosingFrequencyReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DosageRecommendationId")
                        .HasColumnType("integer");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DosageRecommendationId");

                    b.HasIndex("Language", "DosageRecommendationId")
                        .IsUnique();

                    b.ToTable("TranslatedDosingFrequencyReminder");
                });

            modelBuilder.Entity("Medicine.Entities.Models.UserDoctorRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AccpetedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CreatedRequest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MedicineWorkerId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserDoctorRelationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineWorkerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDoctorRelations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.UserMedicineWorkerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserDoctorRelationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserMedicineWorkerLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Medicine.Entities.Models.CourseGroup", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.HasIndex("AuthorId");

                    b.ToTable("CourseGroup");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedActiveElement", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("ActiveElementId")
                        .HasColumnType("integer");

                    b.HasIndex("ActiveElementId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Language", "ActiveElementId")
                        .IsUnique();

                    b.ToTable("TranslatedActiveElement");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedCourse", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId");

                    b.HasIndex("Language", "CourseId")
                        .IsUnique();

                    b.ToTable("TranslatedCourse");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedCourseGroup", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("CourseGroupId")
                        .HasColumnType("integer");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseGroupId");

                    b.HasIndex("Language", "CourseGroupId")
                        .IsUnique();

                    b.ToTable("TranslatedCourseGroup");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDosingFrequency", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("DosingFrequencyId")
                        .HasColumnType("integer");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DosingFrequencyId");

                    b.ToTable("TranslatedDosingFrequency");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDrugs", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<string>("Recomendation")
                        .HasColumnType("text");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DrugId");

                    b.HasIndex("Language", "DrugId")
                        .IsUnique();

                    b.ToTable("TranslatedDrugs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDrugsCategory", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("DrugCategoryId")
                        .HasColumnType("integer");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DrugCategoryId");

                    b.HasIndex("Language", "DrugCategoryId")
                        .IsUnique();

                    b.ToTable("TranslatedDrugsCategory");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedTherapy", b =>
                {
                    b.HasBaseType("Medicine.Entities.Models.Translated.Base.TransatedEntityWithDescription");

                    b.Property<int>("TherapyId")
                        .HasColumnType("integer");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TherapyId");

                    b.HasIndex("Language", "TherapyId")
                        .IsUnique();

                    b.ToTable("TranslatedTherapy");
                });

            modelBuilder.Entity("DrugDrugCategory", b =>
                {
                    b.HasOne("Medicine.Entities.Models.DrugCategory", null)
                        .WithMany()
                        .HasForeignKey("DrugCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Entities.Models.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Medicine.Entities.Models.ActiveElement", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Drug", "Drug")
                        .WithMany("ActiveElements")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Course", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.CourseGroup", "CourseGroup")
                        .WithMany("Courses")
                        .HasForeignKey("CourseGroupID");

                    b.HasOne("Medicine.Entities.Models.Therapy", "Therapy")
                        .WithMany("Courses")
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CourseGroup");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("Medicine.Entities.Models.CourseSettings", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Course", "Course")
                        .WithMany("CourseSettings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosageLog", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.DosingFrequencyReminder", "DosageRecommendation")
                        .WithMany("DosageLogs")
                        .HasForeignKey("DosageRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DosageRecommendation");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequency", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Course", "Course")
                        .WithMany("DosingFrequencies")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Entities.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequencyReminder", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.DosingFrequency", "DosingFrequency")
                        .WithMany("DosingFrequencyReminders")
                        .HasForeignKey("DosingFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Entities.Models.Reminder", "Reminder")
                        .WithMany("DosingFrequencyReminders")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DosingFrequency");

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Drug", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.SimilarDrugs", "SimilarDrugs")
                        .WithMany("SimilarDrugsList")
                        .HasForeignKey("SimilarDrugsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("SimilarDrugs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DrugCategory", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Reminder", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medicine.Entities.Models.ReminderLog", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Reminder", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Therapy", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDosingFrequencyReminder", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.DosingFrequencyReminder", "DosageRecommendation")
                        .WithMany()
                        .HasForeignKey("DosageRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DosageRecommendation");
                });

            modelBuilder.Entity("Medicine.Entities.Models.UserDoctorRelations", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "MedicineWorker")
                        .WithMany()
                        .HasForeignKey("MedicineWorkerId");

                    b.HasOne("Medicine.Entities.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("MedicineWorker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Entities.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Medicine.Entities.Models.CourseGroup", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedActiveElement", b =>
                {
                    b.HasOne("Medicine.Entities.Models.ActiveElement", "ActiveElement")
                        .WithMany("Translations")
                        .HasForeignKey("ActiveElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("ActiveElement");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedCourse", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Course", "Course")
                        .WithMany("Translations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedCourseGroup", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.CourseGroup", "CourseGroup")
                        .WithMany("Translations")
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CourseGroup");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDosingFrequency", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.DosingFrequency", "DosingFrequency")
                        .WithMany("Translations")
                        .HasForeignKey("DosingFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DosingFrequency");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDrugs", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Drug", "Drug")
                        .WithMany("Translations")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedDrugsCategory", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.DrugCategory", "DrugCategory")
                        .WithMany("Translations")
                        .HasForeignKey("DrugCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DrugCategory");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Translated.TranslatedTherapy", b =>
                {
                    b.HasOne("Medicine.Entities.Models.Auth.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Medicine.Entities.Models.Therapy", "Therapy")
                        .WithMany("Translations")
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("Medicine.Entities.Models.ActiveElement", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Course", b =>
                {
                    b.Navigation("CourseSettings");

                    b.Navigation("DosingFrequencies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequency", b =>
                {
                    b.Navigation("DosingFrequencyReminders");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DosingFrequencyReminder", b =>
                {
                    b.Navigation("DosageLogs");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Drug", b =>
                {
                    b.Navigation("ActiveElements");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.DrugCategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Reminder", b =>
                {
                    b.Navigation("DosingFrequencyReminders");
                });

            modelBuilder.Entity("Medicine.Entities.Models.SimilarDrugs", b =>
                {
                    b.Navigation("SimilarDrugsList");
                });

            modelBuilder.Entity("Medicine.Entities.Models.Therapy", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Medicine.Entities.Models.CourseGroup", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
